config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :docs
  
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy] 
  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else  
      render "new"
    end    
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render "edit"
    end    
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
    def find_doc
      @doc = Doc.find(params[:id])
    end
    
    def doc_params
      params.require(:doc).permit(:title, :content)
    end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= form_with(model: @doc, local:true )do |f|
  = f.label :title
  = f.text_field :title 
  %br
  = f.label :content
  = f.text_area :content
  %br
  = f.submit :Upload, class: "button"

app/views/docs/create.html.erb
<h1>Docs#create</h1>
<p>Find me in app/views/docs/create.html.erb</p>

app/views/docs/destroy.html.erb
<h1>Docs#delete</h1>
<p>Find me in app/views/docs/delete.html.erb</p>

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit Doc!
  
  = render "form"
  
  = link_to "All Docs", docs_path
  = link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create your first Doc!
      %p Start creating Documents and Notes to organize your life        
      %button= link_to "Create Doc", new_doc_path  

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc!
  
  = render "form"
  
  = link_to "Cancel", docs_path

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      = link_to "Edit Doc", edit_doc_path(@doc), class: "button"
      = link_to "Delete", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}, class: "button" 

app/views/docs/update.html.erb
<h1>Docs#update</h1>
<p>Find me in app/views/docs/update.html.erb</p>

app/views/layouts/application.html.haml
%html
  %head
    %title Cabinet | Your notes!
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    = csrf_meta_tags 
    = csp_meta_tag
  %body
    %header
      .header_inner
        = link_to "Cabinet", root_path, id: "logo"

        %nav
          - if user_signed_in?
            = link_to "Create Doc", new_doc_path  
            = link_to "Sign Out", destroy_user_session_path, method: :delete

          - else
            = link_to "Log In", new_user_session_path  
    %p.notice= notice
    %p.alert= alert
      
    = yield 
  

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Cabinet
    %p Welcome to your life note's cabinet!
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize and enjoy!
        %p It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to "Join Now", new_user_registration_path